// Every intent registers itself on import. To teach the assistant something
// new, add a file next to these and import it here.
import './studyToday.js'
import './calendar.js'
import './todos.js'
import './conflicts.js'
import './overview.js'
import './stats.js'
import './eventInfo.js'
import './search.js'
import './navigation.js'
import './exams.js'
import './topics.js'
import './insights.js'
import './profile.js'
